"""
    Qovery API

    - Qovery is the fastest way to deploy your full-stack apps on any Cloud provider. - ℹ️ The API is stable and still in development.   # noqa: E501

    The version of the OpenAPI document: 1.0.3
    Contact: support+api+documentation@qovery.com
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import qovery
from qovery.model.threshold_metric_status_enum import ThresholdMetricStatusEnum
globals()['ThresholdMetricStatusEnum'] = ThresholdMetricStatusEnum
from qovery.model.environment_databases_current_metric_storage import EnvironmentDatabasesCurrentMetricStorage


class TestEnvironmentDatabasesCurrentMetricStorage(unittest.TestCase):
    """EnvironmentDatabasesCurrentMetricStorage unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testEnvironmentDatabasesCurrentMetricStorage(self):
        """Test EnvironmentDatabasesCurrentMetricStorage"""
        # FIXME: construct object with mandatory attributes with example values
        # model = EnvironmentDatabasesCurrentMetricStorage()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
