# coding: utf-8

"""
    Qovery API

    - Qovery is the fastest way to deploy your full-stack apps on any Cloud provider. - ℹ️ The API is stable and still in development. 

    The version of the OpenAPI document: 1.0.3
    Contact: support+api+documentation@qovery.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from qovery.models.git_provider_enum import GitProviderEnum  # noqa: E501

class TestGitProviderEnum(unittest.TestCase):
    """GitProviderEnum unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testGitProviderEnum(self):
        """Test GitProviderEnum"""
        # inst = GitProviderEnum()

if __name__ == '__main__':
    unittest.main()
