"""
    Qovery API

    - Qovery is the fastest way to deploy your full-stack apps on any Cloud provider. - ℹ️ The API is stable and still in development.   # noqa: E501

    The version of the OpenAPI document: 1.0.3
    Contact: support+api+documentation@qovery.com
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import qovery
from qovery.model.organization_api_token_scope import OrganizationApiTokenScope
globals()['OrganizationApiTokenScope'] = OrganizationApiTokenScope
from qovery.model.organization_api_token_create_response_all_of import OrganizationApiTokenCreateResponseAllOf


class TestOrganizationApiTokenCreateResponseAllOf(unittest.TestCase):
    """OrganizationApiTokenCreateResponseAllOf unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testOrganizationApiTokenCreateResponseAllOf(self):
        """Test OrganizationApiTokenCreateResponseAllOf"""
        # FIXME: construct object with mandatory attributes with example values
        # model = OrganizationApiTokenCreateResponseAllOf()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
