# coding: utf-8

"""
    Qovery API

    - Qovery is the fastest way to deploy your full-stack apps on any Cloud provider. - ℹ️ The API is stable and still in development. 

    The version of the OpenAPI document: 1.0.3
    Contact: support+api+documentation@qovery.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from qovery.api.organization_event_api import OrganizationEventApi


class TestOrganizationEventApi(unittest.TestCase):
    """OrganizationEventApi unit test stubs"""

    def setUp(self) -> None:
        self.api = OrganizationEventApi()

    def tearDown(self) -> None:
        pass

    def test_get_organization_event_targets(self) -> None:
        """Test case for get_organization_event_targets

        Get available event targets to filter events
        """
        pass

    def test_get_organization_events(self) -> None:
        """Test case for get_organization_events

        Get all events inside the organization
        """
        pass


if __name__ == '__main__':
    unittest.main()
