"""
    Qovery API

    - Qovery is the fastest way to deploy your full-stack apps on any Cloud provider. - ℹ️ The API is stable and still in development.   # noqa: E501

    The version of the OpenAPI document: 1.0.3
    Contact: support+api+documentation@qovery.com
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import qovery
from qovery.model.preview_container_environments_request import PreviewContainerEnvironmentsRequest


class TestPreviewContainerEnvironmentsRequest(unittest.TestCase):
    """PreviewContainerEnvironmentsRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testPreviewContainerEnvironmentsRequest(self):
        """Test PreviewContainerEnvironmentsRequest"""
        # FIXME: construct object with mandatory attributes with example values
        # model = PreviewContainerEnvironmentsRequest()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
