# coding: utf-8

"""
    Qovery API

    - Qovery is the fastest way to deploy your full-stack apps on any Cloud provider. - ℹ️ The API is stable and still in development. 

    The version of the OpenAPI document: 1.0.3
    Contact: support+api+documentation@qovery.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from qovery.api.user_sign_up_api import UserSignUpApi  # noqa: E501


class TestUserSignUpApi(unittest.TestCase):
    """UserSignUpApi unit test stubs"""

    def setUp(self) -> None:
        self.api = UserSignUpApi()  # noqa: E501

    def tearDown(self) -> None:
        pass

    def test_create_user_sign_up(self) -> None:
        """Test case for create_user_sign_up

        Send Sign Up request  # noqa: E501
        """
        pass

    def test_get_user_sign_up(self) -> None:
        """Test case for get_user_sign_up

        Get Sign up information  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
