"""
    Qovery API

    - Qovery is the fastest way to deploy your full-stack apps on any Cloud provider. - ℹ️ The API is stable and still in development.   # noqa: E501

    The version of the OpenAPI document: 1.0.3
    Contact: support+api+documentation@qovery.com
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import qovery
from qovery.model.application_git_repository_response import ApplicationGitRepositoryResponse
from qovery.model.application_port_response import ApplicationPortResponse
from qovery.model.application_port_response_ports import ApplicationPortResponsePorts
from qovery.model.application_storage_response import ApplicationStorageResponse
from qovery.model.application_storage_response_storage import ApplicationStorageResponseStorage
from qovery.model.base_response import BaseResponse
from qovery.model.healthcheck import Healthcheck
from qovery.model.reference_object import ReferenceObject
globals()['ApplicationGitRepositoryResponse'] = ApplicationGitRepositoryResponse
globals()['ApplicationPortResponse'] = ApplicationPortResponse
globals()['ApplicationPortResponsePorts'] = ApplicationPortResponsePorts
globals()['ApplicationStorageResponse'] = ApplicationStorageResponse
globals()['ApplicationStorageResponseStorage'] = ApplicationStorageResponseStorage
globals()['BaseResponse'] = BaseResponse
globals()['Healthcheck'] = Healthcheck
globals()['ReferenceObject'] = ReferenceObject
from qovery.model.application_response import ApplicationResponse


class TestApplicationResponse(unittest.TestCase):
    """ApplicationResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testApplicationResponse(self):
        """Test ApplicationResponse"""
        # FIXME: construct object with mandatory attributes with example values
        # model = ApplicationResponse()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
