"""
    Qovery API

    - Qovery is the fastest way to deploy your full-stack apps on any Cloud provider. - ℹ️ The API is stable and still in development.   # noqa: E501

    The version of the OpenAPI document: 1.0.3
    Contact: support+api+documentation@qovery.com
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import qovery
from qovery.model.organization_custom_role_update_request_project_permissions_inner_permissions_inner import OrganizationCustomRoleUpdateRequestProjectPermissionsInnerPermissionsInner
globals()['OrganizationCustomRoleUpdateRequestProjectPermissionsInnerPermissionsInner'] = OrganizationCustomRoleUpdateRequestProjectPermissionsInnerPermissionsInner
from qovery.model.organization_custom_role_project_permissions_inner import OrganizationCustomRoleProjectPermissionsInner


class TestOrganizationCustomRoleProjectPermissionsInner(unittest.TestCase):
    """OrganizationCustomRoleProjectPermissionsInner unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testOrganizationCustomRoleProjectPermissionsInner(self):
        """Test OrganizationCustomRoleProjectPermissionsInner"""
        # FIXME: construct object with mandatory attributes with example values
        # model = OrganizationCustomRoleProjectPermissionsInner()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
