"""
    Qovery API

    - Qovery is the fastest way to deploy your full-stack apps on any Cloud provider. - ℹ️ The API is stable and still in development.   # noqa: E501

    The version of the OpenAPI document: 1.0.2
    Contact: support+api+documentation@qovery.com
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import qovery
from qovery.model.project_deployment_rule_response import ProjectDeploymentRuleResponse
globals()['ProjectDeploymentRuleResponse'] = ProjectDeploymentRuleResponse
from qovery.model.project_deployment_rule_response_list import ProjectDeploymentRuleResponseList


class TestProjectDeploymentRuleResponseList(unittest.TestCase):
    """ProjectDeploymentRuleResponseList unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testProjectDeploymentRuleResponseList(self):
        """Test ProjectDeploymentRuleResponseList"""
        # FIXME: construct object with mandatory attributes with example values
        # model = ProjectDeploymentRuleResponseList()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
