"""
    Qovery API

    - Qovery is the fastest way to deploy your full-stack apps on any Cloud provider. - ℹ️ The API is stable and still in development.   # noqa: E501

    The version of the OpenAPI document: 1.0.3
    Contact: support+api+documentation@qovery.com
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import qovery
from qovery.model.get_environment_container_current_instance200_response_results_inner import GetEnvironmentContainerCurrentInstance200ResponseResultsInner
globals()['GetEnvironmentContainerCurrentInstance200ResponseResultsInner'] = GetEnvironmentContainerCurrentInstance200ResponseResultsInner
from qovery.model.get_environment_container_current_instance200_response import GetEnvironmentContainerCurrentInstance200Response


class TestGetEnvironmentContainerCurrentInstance200Response(unittest.TestCase):
    """GetEnvironmentContainerCurrentInstance200Response unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testGetEnvironmentContainerCurrentInstance200Response(self):
        """Test GetEnvironmentContainerCurrentInstance200Response"""
        # FIXME: construct object with mandatory attributes with example values
        # model = GetEnvironmentContainerCurrentInstance200Response()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
