"""
    Qovery API

    - Qovery is the fastest way to deploy your full-stack apps on any Cloud provider. - ℹ️ The API is stable and still in development.   # noqa: E501

    The version of the OpenAPI document: 1.0.3
    Contact: support+api+documentation@qovery.com
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import qovery
from qovery.model.environment_logs import EnvironmentLogs
globals()['EnvironmentLogs'] = EnvironmentLogs
from qovery.model.environment_logs_response_list import EnvironmentLogsResponseList


class TestEnvironmentLogsResponseList(unittest.TestCase):
    """EnvironmentLogsResponseList unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testEnvironmentLogsResponseList(self):
        """Test EnvironmentLogsResponseList"""
        # FIXME: construct object with mandatory attributes with example values
        # model = EnvironmentLogsResponseList()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
