"""
    Qovery API

    - Qovery is the fastest way to deploy your full-stack apps on any Cloud provider. - ℹ️ The API is stable and still in development.   # noqa: E501

    The version of the OpenAPI document: 1.0.3
    Contact: support+api+documentation@qovery.com
    Generated by: https://openapi-generator.tech
"""


import unittest

import qovery
from qovery.api.application_deployment_restriction_api import ApplicationDeploymentRestrictionApi  # noqa: E501


class TestApplicationDeploymentRestrictionApi(unittest.TestCase):
    """ApplicationDeploymentRestrictionApi unit test stubs"""

    def setUp(self):
        self.api = ApplicationDeploymentRestrictionApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_create_application_deployment_restriction(self):
        """Test case for create_application_deployment_restriction

        Create an application deployment restriction  # noqa: E501
        """
        pass

    def test_delete_application_deployment_restriction(self):
        """Test case for delete_application_deployment_restriction

        Delete an application deployment restriction  # noqa: E501
        """
        pass

    def test_edit_application_deployment_restriction(self):
        """Test case for edit_application_deployment_restriction

        Edit an application deployment restriction  # noqa: E501
        """
        pass

    def test_get_application_deployment_restrictions(self):
        """Test case for get_application_deployment_restrictions

        Get application deployment restrictions  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
