# coding: utf-8

"""
    Qovery API

    - Qovery is the fastest way to deploy your full-stack apps on any Cloud provider. - ℹ️ The API is stable and still in development. 

    The version of the OpenAPI document: 1.0.3
    Contact: support+api+documentation@qovery.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from qovery.api.project_main_calls_api import ProjectMainCallsApi


class TestProjectMainCallsApi(unittest.TestCase):
    """ProjectMainCallsApi unit test stubs"""

    def setUp(self) -> None:
        self.api = ProjectMainCallsApi()

    def tearDown(self) -> None:
        pass

    def test_delete_project(self) -> None:
        """Test case for delete_project

        Delete a project
        """
        pass

    def test_edit_project(self) -> None:
        """Test case for edit_project

        Edit a project
        """
        pass

    def test_get_project(self) -> None:
        """Test case for get_project

        Get project by ID
        """
        pass


if __name__ == '__main__':
    unittest.main()
