"""
    Qovery API

    - Qovery is the fastest way to deploy your full-stack apps on any Cloud provider. - ℹ️ The API is stable and still in development.   # noqa: E501

    The version of the OpenAPI document: 1.0.3
    Contact: support+api+documentation@qovery.com
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import qovery
from qovery.model.base import Base
from qovery.model.helm_repository_kind_enum import HelmRepositoryKindEnum
from qovery.model.helm_repository_response_all_of import HelmRepositoryResponseAllOf
globals()['Base'] = Base
globals()['HelmRepositoryKindEnum'] = HelmRepositoryKindEnum
globals()['HelmRepositoryResponseAllOf'] = HelmRepositoryResponseAllOf
from qovery.model.helm_repository_response import HelmRepositoryResponse


class TestHelmRepositoryResponse(unittest.TestCase):
    """HelmRepositoryResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testHelmRepositoryResponse(self):
        """Test HelmRepositoryResponse"""
        # FIXME: construct object with mandatory attributes with example values
        # model = HelmRepositoryResponse()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
