"""
    Qovery API

    - Qovery is the fastest way to deploy your full-stack apps on any Cloud provider. - ℹ️ The API is stable and still in development.   # noqa: E501

    The version of the OpenAPI document: 1.0.3
    Contact: support+api+documentation@qovery.com
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import qovery
from qovery.model.database_type_enum import DatabaseTypeEnum


class TestDatabaseTypeEnum(unittest.TestCase):
    """DatabaseTypeEnum unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testDatabaseTypeEnum(self):
        """Test DatabaseTypeEnum"""
        # FIXME: construct object with mandatory attributes with example values
        # model = DatabaseTypeEnum()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
