"""
    Qovery API

    - Qovery is the fastest way to deploy your full-stack apps on any Cloud provider. - ℹ️ The API is stable and still in development.   # noqa: E501

    The version of the OpenAPI document: 1.0.1
    Contact: support+api+documentation@qovery.com
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import qovery
from qovery.model.paid_usage_response import PaidUsageResponse
globals()['PaidUsageResponse'] = PaidUsageResponse
from qovery.model.paid_usage import PaidUsage


class TestPaidUsage(unittest.TestCase):
    """PaidUsage unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testPaidUsage(self):
        """Test PaidUsage"""
        # FIXME: construct object with mandatory attributes with example values
        # model = PaidUsage()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
