"""
    Qovery API

    - Qovery is the fastest way to deploy your full-stack apps on any Cloud provider. - ℹ️ The API is stable and still in development.   # noqa: E501

    The version of the OpenAPI document: 1.0.3
    Contact: support+api+documentation@qovery.com
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import qovery
from qovery.model.helm_response_all_of_source_repository_repository import HelmResponseAllOfSourceRepositoryRepository
globals()['HelmResponseAllOfSourceRepositoryRepository'] = HelmResponseAllOfSourceRepositoryRepository
from qovery.model.helm_response_all_of_source_repository import HelmResponseAllOfSourceRepository


class TestHelmResponseAllOfSourceRepository(unittest.TestCase):
    """HelmResponseAllOfSourceRepository unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testHelmResponseAllOfSourceRepository(self):
        """Test HelmResponseAllOfSourceRepository"""
        # FIXME: construct object with mandatory attributes with example values
        # model = HelmResponseAllOfSourceRepository()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
