"""
    Qovery API

    - Qovery is the fastest way to deploy your full-stack apps on any Cloud provider. - ℹ️ The API is stable and still in development.   # noqa: E501

    The version of the OpenAPI document: 1.0.3
    Contact: support+api+documentation@qovery.com
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import qovery
from qovery.model.application_git_repository_request import ApplicationGitRepositoryRequest
globals()['ApplicationGitRepositoryRequest'] = ApplicationGitRepositoryRequest
from qovery.model.helm_request_all_of_source_git import HelmRequestAllOfSourceGit


class TestHelmRequestAllOfSourceGit(unittest.TestCase):
    """HelmRequestAllOfSourceGit unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testHelmRequestAllOfSourceGit(self):
        """Test HelmRequestAllOfSourceGit"""
        # FIXME: construct object with mandatory attributes with example values
        # model = HelmRequestAllOfSourceGit()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
