"""
    Qovery API

    - Qovery is the fastest way to deploy your full-stack apps on any Cloud provider. - ℹ️ The API is stable and still in development.   # noqa: E501

    The version of the OpenAPI document: 1.0.3
    Contact: support+api+documentation@qovery.com
    Generated by: https://openapi-generator.tech
"""


import unittest

import qovery
from qovery.api.organization_webhook_api import OrganizationWebhookApi  # noqa: E501


class TestOrganizationWebhookApi(unittest.TestCase):
    """OrganizationWebhookApi unit test stubs"""

    def setUp(self):
        self.api = OrganizationWebhookApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_create_organization_webhook(self):
        """Test case for create_organization_webhook

        Create an organization webhook  # noqa: E501
        """
        pass

    def test_delete_organization_webhook(self):
        """Test case for delete_organization_webhook

        Delete organization webhook  # noqa: E501
        """
        pass

    def test_edit_organization_webhook(self):
        """Test case for edit_organization_webhook

        Edit an organization webhook  # noqa: E501
        """
        pass

    def test_get_organization_webhook(self):
        """Test case for get_organization_webhook

        Get an Organization webhook  # noqa: E501
        """
        pass

    def test_list_organization_web_hooks(self):
        """Test case for list_organization_web_hooks

        List organization webhooks  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
