"""
    Qovery API

    - Qovery is the fastest way to deploy your full-stack apps on any Cloud provider. - ℹ️ The API is stable and still in development.   # noqa: E501

    The version of the OpenAPI document: 1.0.3
    Contact: support+api+documentation@qovery.com
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import qovery
from qovery.model.job_request_all_of_schedule_cronjob import JobRequestAllOfScheduleCronjob


class TestJobRequestAllOfScheduleCronjob(unittest.TestCase):
    """JobRequestAllOfScheduleCronjob unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testJobRequestAllOfScheduleCronjob(self):
        """Test JobRequestAllOfScheduleCronjob"""
        # FIXME: construct object with mandatory attributes with example values
        # model = JobRequestAllOfScheduleCronjob()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
