"""
    Qovery API

    - Qovery is the fastest way to deploy your full-stack apps on any Cloud provider. - ℹ️ The API is stable and still in development.   # noqa: E501

    The version of the OpenAPI document: 1.0.3
    Contact: support+api+documentation@qovery.com
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import qovery
from qovery.model.application_edit_request_all_of import ApplicationEditRequestAllOf
from qovery.model.application_git_repository_request import ApplicationGitRepositoryRequest
from qovery.model.application_storage import ApplicationStorage
from qovery.model.application_storage_storage_inner import ApplicationStorageStorageInner
from qovery.model.build_mode_enum import BuildModeEnum
from qovery.model.build_pack_language_enum import BuildPackLanguageEnum
from qovery.model.healthcheck import Healthcheck
from qovery.model.service_port import ServicePort
from qovery.model.service_port_ports_inner import ServicePortPortsInner
globals()['ApplicationEditRequestAllOf'] = ApplicationEditRequestAllOf
globals()['ApplicationGitRepositoryRequest'] = ApplicationGitRepositoryRequest
globals()['ApplicationStorage'] = ApplicationStorage
globals()['ApplicationStorageStorageInner'] = ApplicationStorageStorageInner
globals()['BuildModeEnum'] = BuildModeEnum
globals()['BuildPackLanguageEnum'] = BuildPackLanguageEnum
globals()['Healthcheck'] = Healthcheck
globals()['ServicePort'] = ServicePort
globals()['ServicePortPortsInner'] = ServicePortPortsInner
from qovery.model.application_edit_request import ApplicationEditRequest


class TestApplicationEditRequest(unittest.TestCase):
    """ApplicationEditRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testApplicationEditRequest(self):
        """Test ApplicationEditRequest"""
        # FIXME: construct object with mandatory attributes with example values
        # model = ApplicationEditRequest()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
