"""
    Qovery API

    - Qovery is the fastest way to deploy your full-stack apps on any Cloud provider. - ℹ️ The API is stable and still in development.   # noqa: E501

    The version of the OpenAPI document: 1.0.3
    Contact: support+api+documentation@qovery.com
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import qovery
from qovery.model.job_request_all_of_schedule import JobRequestAllOfSchedule
from qovery.model.job_response_all_of_source import JobResponseAllOfSource
from qovery.model.reference_object import ReferenceObject
globals()['JobRequestAllOfSchedule'] = JobRequestAllOfSchedule
globals()['JobResponseAllOfSource'] = JobResponseAllOfSource
globals()['ReferenceObject'] = ReferenceObject
from qovery.model.job_response_all_of import JobResponseAllOf


class TestJobResponseAllOf(unittest.TestCase):
    """JobResponseAllOf unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testJobResponseAllOf(self):
        """Test JobResponseAllOf"""
        # FIXME: construct object with mandatory attributes with example values
        # model = JobResponseAllOf()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
