"""
    Qovery API

    - Qovery is the fastest way to deploy your full-stack apps on any Cloud provider. - ℹ️ The API is stable and still in development.   # noqa: E501

    The version of the OpenAPI document: 1.0.3
    Contact: support+api+documentation@qovery.com
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import qovery
from qovery.model.base import Base
from qovery.model.environment_variable_all_of import EnvironmentVariableAllOf
from qovery.model.environment_variable_all_of_aliased_variable import EnvironmentVariableAllOfAliasedVariable
from qovery.model.environment_variable_all_of_overridden_variable import EnvironmentVariableAllOfOverriddenVariable
from qovery.model.environment_variable_request import EnvironmentVariableRequest
from qovery.model.environment_variable_scope_enum import EnvironmentVariableScopeEnum
from qovery.model.linked_service_type_enum import LinkedServiceTypeEnum
globals()['Base'] = Base
globals()['EnvironmentVariableAllOf'] = EnvironmentVariableAllOf
globals()['EnvironmentVariableAllOfAliasedVariable'] = EnvironmentVariableAllOfAliasedVariable
globals()['EnvironmentVariableAllOfOverriddenVariable'] = EnvironmentVariableAllOfOverriddenVariable
globals()['EnvironmentVariableRequest'] = EnvironmentVariableRequest
globals()['EnvironmentVariableScopeEnum'] = EnvironmentVariableScopeEnum
globals()['LinkedServiceTypeEnum'] = LinkedServiceTypeEnum
from qovery.model.environment_variable import EnvironmentVariable


class TestEnvironmentVariable(unittest.TestCase):
    """EnvironmentVariable unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testEnvironmentVariable(self):
        """Test EnvironmentVariable"""
        # FIXME: construct object with mandatory attributes with example values
        # model = EnvironmentVariable()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
