"""
    Qovery API

    - Qovery is the fastest way to deploy your full-stack apps on any Cloud provider. - ℹ️ The API is stable and still in development.   # noqa: E501

    The version of the OpenAPI document: 1.0.3
    Contact: support+api+documentation@qovery.com
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import qovery
from qovery.model.deployment_history_database import DeploymentHistoryDatabase
globals()['DeploymentHistoryDatabase'] = DeploymentHistoryDatabase
from qovery.model.list_database_deployment_history200_response_all_of import ListDatabaseDeploymentHistory200ResponseAllOf


class TestListDatabaseDeploymentHistory200ResponseAllOf(unittest.TestCase):
    """ListDatabaseDeploymentHistory200ResponseAllOf unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testListDatabaseDeploymentHistory200ResponseAllOf(self):
        """Test ListDatabaseDeploymentHistory200ResponseAllOf"""
        # FIXME: construct object with mandatory attributes with example values
        # model = ListDatabaseDeploymentHistory200ResponseAllOf()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
