"""
    Qovery API

    - Qovery is the fastest way to deploy your full-stack apps on any Cloud provider. - ℹ️ The API is stable and still in development.   # noqa: E501

    The version of the OpenAPI document: 1.0.3
    Contact: support+api+documentation@qovery.com
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import qovery
from qovery.model.application_git_repository_response import ApplicationGitRepositoryResponse
from qovery.model.build_mode_enum import BuildModeEnum
from qovery.model.build_pack_language_enum import BuildPackLanguageEnum
from qovery.model.healthcheck import Healthcheck
from qovery.model.reference_object import ReferenceObject
globals()['ApplicationGitRepositoryResponse'] = ApplicationGitRepositoryResponse
globals()['BuildModeEnum'] = BuildModeEnum
globals()['BuildPackLanguageEnum'] = BuildPackLanguageEnum
globals()['Healthcheck'] = Healthcheck
globals()['ReferenceObject'] = ReferenceObject
from qovery.model.application_response_all_of import ApplicationResponseAllOf


class TestApplicationResponseAllOf(unittest.TestCase):
    """ApplicationResponseAllOf unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testApplicationResponseAllOf(self):
        """Test ApplicationResponseAllOf"""
        # FIXME: construct object with mandatory attributes with example values
        # model = ApplicationResponseAllOf()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
