# coding: utf-8

"""
    Qovery API

    - Qovery is the fastest way to deploy your full-stack apps on any Cloud provider. - ℹ️ The API is stable and still in development. 

    The version of the OpenAPI document: 1.0.3
    Contact: support+api+documentation@qovery.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from qovery.api.database_deployment_history_api import DatabaseDeploymentHistoryApi  # noqa: E501


class TestDatabaseDeploymentHistoryApi(unittest.TestCase):
    """DatabaseDeploymentHistoryApi unit test stubs"""

    def setUp(self) -> None:
        self.api = DatabaseDeploymentHistoryApi()  # noqa: E501

    def tearDown(self) -> None:
        pass

    def test_list_database_deployment_history(self) -> None:
        """Test case for list_database_deployment_history

        List database deploys  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
