"""
    Qovery API

    - Qovery is the fastest way to deploy your full-stack apps on any Cloud provider. - ℹ️ The API is stable and still in development.   # noqa: E501

    The version of the OpenAPI document: 1.0.3
    Contact: support+api+documentation@qovery.com
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import qovery
from qovery.model.deployment_history_response import DeploymentHistoryResponse
globals()['DeploymentHistoryResponse'] = DeploymentHistoryResponse
from qovery.model.deployment_history_paginated_response_list_all_of import DeploymentHistoryPaginatedResponseListAllOf


class TestDeploymentHistoryPaginatedResponseListAllOf(unittest.TestCase):
    """DeploymentHistoryPaginatedResponseListAllOf unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testDeploymentHistoryPaginatedResponseListAllOf(self):
        """Test DeploymentHistoryPaginatedResponseListAllOf"""
        # FIXME: construct object with mandatory attributes with example values
        # model = DeploymentHistoryPaginatedResponseListAllOf()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
