"""
    Qovery API

    - Qovery is the fastest way to deploy your full-stack apps on any Cloud provider. - ℹ️ The API is stable and still in development.   # noqa: E501

    The version of the OpenAPI document: 1.0.3
    Contact: support+api+documentation@qovery.com
    Generated by: https://openapi-generator.tech
"""


import unittest

import qovery
from qovery.api.container_custom_domain_api import ContainerCustomDomainApi  # noqa: E501


class TestContainerCustomDomainApi(unittest.TestCase):
    """ContainerCustomDomainApi unit test stubs"""

    def setUp(self):
        self.api = ContainerCustomDomainApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_create_container_custom_domain(self):
        """Test case for create_container_custom_domain

        Add custom domain to the container.  # noqa: E501
        """
        pass

    def test_delete_container_custom_domain(self):
        """Test case for delete_container_custom_domain

        Delete a Custom Domain  # noqa: E501
        """
        pass

    def test_edit_container_custom_domain(self):
        """Test case for edit_container_custom_domain

        Edit a Custom Domain  # noqa: E501
        """
        pass

    def test_get_container_custom_domain_status(self):
        """Test case for get_container_custom_domain_status

        Get Custom Domain status  # noqa: E501
        """
        pass

    def test_list_container_custom_domain(self):
        """Test case for list_container_custom_domain

        List container custom domains  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
