"""
    Qovery API

    - Qovery is the fastest way to deploy your full-stack apps on any Cloud provider. - ℹ️ The API is stable and still in development.   # noqa: E501

    The version of the OpenAPI document: 1.0.2
    Contact: support+api+documentation@qovery.com
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import qovery
from qovery.model.project_project_id_deployment_rule_order_project_deployment_rule_ids_in_order import ProjectProjectIdDeploymentRuleOrderProjectDeploymentRuleIdsInOrder


class TestProjectProjectIdDeploymentRuleOrderProjectDeploymentRuleIdsInOrder(unittest.TestCase):
    """ProjectProjectIdDeploymentRuleOrderProjectDeploymentRuleIdsInOrder unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testProjectProjectIdDeploymentRuleOrderProjectDeploymentRuleIdsInOrder(self):
        """Test ProjectProjectIdDeploymentRuleOrderProjectDeploymentRuleIdsInOrder"""
        # FIXME: construct object with mandatory attributes with example values
        # model = ProjectProjectIdDeploymentRuleOrderProjectDeploymentRuleIdsInOrder()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
