"""
    Qovery API

    - Qovery is the fastest way to deploy your full-stack apps on any Cloud provider. - ℹ️ The API is stable and still in development.   # noqa: E501

    The version of the OpenAPI document: 1.0.3
    Contact: support+api+documentation@qovery.com
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import qovery
from qovery.model.helm_git_repository_request import HelmGitRepositoryRequest
from qovery.model.helm_request_all_of_values_override import HelmRequestAllOfValuesOverride
globals()['HelmGitRepositoryRequest'] = HelmGitRepositoryRequest
globals()['HelmRequestAllOfValuesOverride'] = HelmRequestAllOfValuesOverride
from qovery.model.helm_request_all_of import HelmRequestAllOf


class TestHelmRequestAllOf(unittest.TestCase):
    """HelmRequestAllOf unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testHelmRequestAllOf(self):
        """Test HelmRequestAllOf"""
        # FIXME: construct object with mandatory attributes with example values
        # model = HelmRequestAllOf()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
