"""
    Qovery API

    - Qovery is the fastest way to deploy your full-stack apps on any Cloud provider. - ℹ️ The API is stable and still in development.   # noqa: E501

    The version of the OpenAPI document: 1.0.3
    Contact: support+api+documentation@qovery.com
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import qovery
from qovery.model.available_container_registry_response import AvailableContainerRegistryResponse
globals()['AvailableContainerRegistryResponse'] = AvailableContainerRegistryResponse
from qovery.model.list_available_container_registry200_response import ListAvailableContainerRegistry200Response


class TestListAvailableContainerRegistry200Response(unittest.TestCase):
    """ListAvailableContainerRegistry200Response unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testListAvailableContainerRegistry200Response(self):
        """Test ListAvailableContainerRegistry200Response"""
        # FIXME: construct object with mandatory attributes with example values
        # model = ListAvailableContainerRegistry200Response()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
