# coding: utf-8

"""
    Qovery API

    - Qovery is the fastest way to deploy your full-stack apps on any Cloud provider. - ℹ️ The API is stable and still in development. 

    The version of the OpenAPI document: 1.0.3
    Contact: support+api+documentation@qovery.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from datetime import datetime
from typing import Any, ClassVar, Dict, List, Optional
from pydantic import BaseModel, StrictBool, StrictStr
from pydantic import Field
from qovery.models.git_provider_enum import GitProviderEnum
try:
    from typing import Self
except ImportError:
    from typing_extensions import Self

class ApplicationGitRepository(BaseModel):
    """
    ApplicationGitRepository
    """ # noqa: E501
    has_access: Optional[StrictBool] = None
    provider: GitProviderEnum
    owner: StrictStr
    url: StrictStr
    name: StrictStr = Field(description="repository name")
    branch: Optional[StrictStr] = None
    root_path: Optional[StrictStr] = None
    deployed_commit_id: Optional[StrictStr] = Field(default=None, description="Git commit ID corresponding to the deployed version of the app")
    deployed_commit_date: Optional[datetime] = Field(default=None, description="Git commit date corresponding to the deployed version of the app")
    deployed_commit_contributor: Optional[StrictStr] = Field(default=None, description="Git commit user corresponding to the deployed version of the app")
    deployed_commit_tag: Optional[StrictStr] = None
    git_token_id: Optional[StrictStr] = None
    git_token_name: Optional[StrictStr] = None
    __properties: ClassVar[List[str]] = ["has_access", "provider", "owner", "url", "name", "branch", "root_path", "deployed_commit_id", "deployed_commit_date", "deployed_commit_contributor", "deployed_commit_tag", "git_token_id", "git_token_name"]

    model_config = {
        "populate_by_name": True,
        "validate_assignment": True,
        "protected_namespaces": (),
    }


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of ApplicationGitRepository from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        * OpenAPI `readOnly` fields are excluded.
        """
        _dict = self.model_dump(
            by_alias=True,
            exclude={
                "deployed_commit_date",
            },
            exclude_none=True,
        )
        # set to None if git_token_id (nullable) is None
        # and model_fields_set contains the field
        if self.git_token_id is None and "git_token_id" in self.model_fields_set:
            _dict['git_token_id'] = None

        # set to None if git_token_name (nullable) is None
        # and model_fields_set contains the field
        if self.git_token_name is None and "git_token_name" in self.model_fields_set:
            _dict['git_token_name'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Dict) -> Self:
        """Create an instance of ApplicationGitRepository from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "has_access": obj.get("has_access"),
            "provider": obj.get("provider"),
            "owner": obj.get("owner"),
            "url": obj.get("url"),
            "name": obj.get("name"),
            "branch": obj.get("branch"),
            "root_path": obj.get("root_path"),
            "deployed_commit_id": obj.get("deployed_commit_id"),
            "deployed_commit_date": obj.get("deployed_commit_date"),
            "deployed_commit_contributor": obj.get("deployed_commit_contributor"),
            "deployed_commit_tag": obj.get("deployed_commit_tag"),
            "git_token_id": obj.get("git_token_id"),
            "git_token_name": obj.get("git_token_name")
        })
        return _obj


