# coding: utf-8

"""
    Qovery API

    - Qovery is the fastest way to deploy your full-stack apps on any Cloud provider. - ℹ️ The API is stable and still in development. 

    The version of the OpenAPI document: 1.0.3
    Contact: support+api+documentation@qovery.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import json
import pprint
import re  # noqa: F401
from aenum import Enum, no_arg





class OrganizationWebhookEventEnum(str, Enum):
    """
    Events to subscribe to and send to the `target_url`. - `DEPLOYMENT_STARTED` send an event when a deployment is started and going to be executed - `DEPLOYMENT_CANCELLED` send an event when a deployment is cancelled - `DEPLOYMENT_FAILURE` send an event when a deployment failed - `DEPLOYMENT_SUCCESSFUL` send an event when a deployment is successful 
    """

    """
    allowed enum values
    """
    DEPLOYMENT_STARTED = 'DEPLOYMENT_STARTED'
    DEPLOYMENT_CANCELLED = 'DEPLOYMENT_CANCELLED'
    DEPLOYMENT_FAILURE = 'DEPLOYMENT_FAILURE'
    DEPLOYMENT_SUCCESSFUL = 'DEPLOYMENT_SUCCESSFUL'

    @classmethod
    def from_json(cls, json_str: str) -> OrganizationWebhookEventEnum:
        """Create an instance of OrganizationWebhookEventEnum from a JSON string"""
        return OrganizationWebhookEventEnum(json.loads(json_str))


