# coding: utf-8

"""
    Qovery API

    - Qovery is the fastest way to deploy your full-stack apps on any Cloud provider. - ℹ️ The API is stable and still in development. 

    The version of the OpenAPI document: 1.0.3
    Contact: support+api+documentation@qovery.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import json
import pprint
import re  # noqa: F401
from aenum import Enum, no_arg





class StepMetricStatusEnum(str, Enum):
    """
    The status of completion for the step: - SUCCESS: The step completed successfully. - ERROR: The step completed with an error. - CANCEL: The step was canceled. - SKIP: The step was skipped because it was not necessary. 
    """

    """
    allowed enum values
    """
    SUCCESS = 'SUCCESS'
    ERROR = 'ERROR'
    CANCEL = 'CANCEL'
    SKIP = 'SKIP'

    @classmethod
    def from_json(cls, json_str: str) -> StepMetricStatusEnum:
        """Create an instance of StepMetricStatusEnum from a JSON string"""
        return StepMetricStatusEnum(json.loads(json_str))


